
name: Deploy App Infra
run-name: Deploy App Infra to ${{ vars.APP_NAME }} by @${{ github.actor }}
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      # repo_uri:
      #   required: true
      #   type: string
      # db_certs:
      #   required: true
      #   type: string
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: './deployment/app'
    permissions:
      contents: read
      id-token: write # Required for Workload Identity Federation
    env:
      TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      TF_VAR_aws_region: ${{ vars.AWS_REGION }}
      TF_VAR_gcp_region: ${{ vars.GCP_REGION }}
      TF_VAR_state_management_bucket_name: ${{ secrets.STATE_MANAGEMENT_BUCKET_NAME }}
      TF_VAR_state_management_prefix: ${{ inputs.environment }}
      TF_VAR_project: ${{ vars.APP_NAME }}
      TF_VAR_environment: ${{ inputs.environment }}
      TF_VAR_db_host: ${{ secrets.DATABASE_HOST }}
      TF_VAR_db_name: ${{ vars.APP_NAME }}-${{ inputs.environment }}-${{ vars.GCP_REGION }}-db
      TF_VAR_db_password: ${{ secrets.POSTGRES_PASSWORD }}
      TF_VAR_db_username: ${{ vars.POSTGRES_USER }}
      TF_VAR_image_tag: ${{ vars.APP_NAME }}:${GITHUB_SHA::7}
      TF_LOG: DEBUG

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_WORKLOAD_SERVICE_ACCOUNT }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main # Or a specific version
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v3'
        with:
          version: '>= 363.0.0'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GCP Artifact Registry
        run: |-
            gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest

      - name: Initialise OpenTofu
        run: tofu fmt -check

      - name: OpenTofu Init
        run: tofu init

      - name: OpenTofu Validate
        run: tofu validate

      # - name: OpenTofu Refresh
      #   run: tofu refresh

      - name: Write CA Certificate to Host Using Tofu Output
        run: |
          echo "pwd - $(pwd)"
          cd ${{ github.workspace }}/deployment/data
          tofu init
          echo "$(tofu output -raw db_client_cert)" > db_ca.crt
          echo "pwd - $(pwd)"

      - name: Build, Tag, and Push Docker Image to Container Repository Using Tofu Output
        run: |-
          echo "pwd - $(pwd)"
          cd ${{ github.workspace }}/deployment/data
          tofu init
          repo_uri="$(tofu output -raw artifact_repo_uri)"
          echo "repo_uri - ${repo_uri}"
          image_name="${repo_uri}/${{ env.TF_VAR_image_tag }}"
          echo "image_name - ${image_name}"

          cd ${{ github.workspace }}/apps/api
          docker build . -t "${image_name}"
          docker push "${image_name}"
          echo "pwd - $(pwd)"


      - name: OpenTofu Plan
        run: |
          echo "pwd - $(pwd)"
          tofu plan -out=tfplan

      - name: Post OpenTofu Plan
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          # COMMENT=$(tofu show -json tfplan)
          COMMENT=$(tofu show tfplan)
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"

          curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST $COMMENT_URL -d "{\"body\":\"$COMMENT\"}"

      - name: OpenTofu Apply
        run: tofu apply -auto-approve tfplan
