
name: Deploy dev Listah API to AWS on pull request
run-name: Deploy to ${{ vars.APP_NAME }} by @${{ github.actor }}
on:
  pull_request:
    branches: [ "main" ]
env:
  ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  REGION: ${{ vars.AWS_REGION }} # TODO: update to your region
  SERVICE: ${{ vars.APP_NAME }} # TODO: update to your service name
  IMAGE_NAME: ${{ vars.APP_NAME }}


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: './apps/api/'
    permissions:
      contents: read
      id-token: write # Required for Workload Identity Federation
    env:
      IMAGE_TAG: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.AWS_ECR_FULL_REPO_NAME }}:${GITHUB_SHA::7}
      DB_CERT: ${{ secrets.DB_CA_CERT }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      ECR_FULL_REPO_NAME: ${{ vars.AWS_ECR_FULL_REPO_NAME }}
      # ECR_FULL_REPO_NAME: ${{ vars.AWS_ECR_FULL_REPO_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Write CA certificate
        run: echo "${{ env.DB_CERT }}" > db_ca.crt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main # Or a specific version
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ env.ACCOUNT_ID }}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build, tag, and push Docker image
        run: |-
          docker build . -t "${{ env.IMAGE_TAG }}"
          docker push "${{ env.IMAGE_TAG }}"
