
name: Deploy Data Infra
run-name: Deploy Data Infra to ${{ vars.APP_NAME }} by @${{ github.actor }}
on:
  workflow_call:
    inputs:
      dpl-env:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  deploy-data:
    runs-on: ubuntu-latest
    # environment: ${{ inputs.dpl-env }}
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: './deployment/data'
    permissions:
      contents: read
      id-token: write # Required for Workload Identity Federation
    env:
      TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      TF_VAR_aws_region: ${{ vars.AWS_REGION }}
      TF_VAR_gcp_region: ${{ vars.GCP_REGION }}
      TF_VAR_state_management_bucket_name: ${{ secrets.STATE_MANAGEMENT_BUCKET_NAME }}
      TF_VAR_state_management_prefix: dev
      TF_VAR_project: ${{ vars.APP_NAME }}
      TF_VAR_environment: dev
      TF_VAR_instance_tier: ${{ vars.DB_INSTANCE_TIER }}
      TF_VAR_root_password: ${{ secrets.POSTGRES_PASSWORD }}
      TF_VAR_user_password: ${{ secrets.POSTGRES_PASSWORD }}
      TF_VAR_username: ${{ vars.POSTGRES_USER }}
      TF_VAR_db_edition: "ENTERPRISE"
      TF_LOG: DEBUG

    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_WORKLOAD_SERVICE_ACCOUNT }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main # Or a specific version
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest

      - name: OpenTofu Format
        run: tofu fmt -check

      - name: OpenTofu Init
        run: tofu init

      - name: OpenTofu Validate
        run: tofu validate

      - name: OpenTofu Plan
        run: tofu plan -out=tfplan

      # - name: OpenTofu Plan
      #   run: PLAN_OUTPUT=$(tofu plan  &> /dev/stdout)

      - name: Post OpenTofu Plan
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          # COMMENT=$(tofu show -json tfplan)
          COMMENT=$(tofu show tfplan)
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"

          curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST $COMMENT_URL -d "{\"body\":\"$COMMENT\"}"

      - name: OpenTofu Apply
        run: tofu apply -auto-approve tfplan
