
name: Deploy Data Infra
run-name: Deploy Data Infra to ${{ vars.APP_NAME }} by @${{ github.actor }}
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    outputs:
      gcp_container_repo_uri:
        description: "Uri of artifactory registry repository"
        value: ${{ jobs.deploy-data.outputs.gcp_container_repo_uri}}
jobs:
  deploy-data:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: './deployment/data'
    permissions:
      contents: read
      id-token: write # Required for Workload Identity Federation
    env:
      TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      TF_VAR_aws_region: ${{ vars.AWS_REGION }}
      TF_VAR_gcp_region: ${{ vars.GCP_REGION }}
      TF_VAR_state_management_bucket_name: ${{ secrets.STATE_MANAGEMENT_BUCKET_NAME }}
      TF_VAR_state_management_prefix: ${{ inputs.environment }}
      TF_VAR_project: ${{ vars.APP_NAME }}
      TF_VAR_environment: ${{ inputs.environment }}
      TF_VAR_instance_tier: ${{ vars.DB_INSTANCE_TIER }}
      TF_VAR_db_name: ${{ vars.APP_NAME }}-${{ inputs.environment }}-${{ vars.GCP_REGION }}-db
      TF_VAR_root_password: ${{ secrets.POSTGRES_PASSWORD }}
      TF_VAR_user_password: ${{ secrets.POSTGRES_PASSWORD }}
      TF_VAR_username: ${{ vars.POSTGRES_USER }}
      TF_VAR_db_edition: "ENTERPRISE"
      TF_LOG: DEBUG
    outputs:
      repo_uri: ${{ steps.tofu_apply.gcp_container_repo_uri }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_WORKLOAD_SERVICE_ACCOUNT }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main # Or a specific version
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest

      - name: OpenTofu Format
        run: tofu fmt -check

      - name: OpenTofu Init
        run: tofu init

      - name: OpenTofu Validate
        run: tofu validate

      - name: OpenTofu Plan
        run: tofu plan -out=tfplan

      # - name: OpenTofu Plan
      #   run: PLAN_OUTPUT=$(tofu plan  &> /dev/stdout)

      - name: Post OpenTofu Plan
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          # COMMENT=$(tofu show -json tfplan)
          COMMENT=$(tofu show tfplan)
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"

          curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST $COMMENT_URL -d "{\"body\":\"$COMMENT\"}"

      - id: tofu_apply
        name: OpenTofu Apply
        run:  |
          tofu apply -auto-approve tfplan

      - id: view_outputs1
        name: View Outputs 1
        run:  |
          echo " Output - "$(tofu output -raw artifact_repo_uri)""
          # echo " val="$(tofu output -raw artifact_repo_uri)""
          # echo " val - $val"
          echo "repo_uri="$(tofu output -raw artifact_repo_uri)"" >> $GITHUB_OUTPUT
          echo "GITHUB_OUTPUT - $GITHUB_OUTPUT"
          echo "GITHUB_OUTPUT content - $(cat $GITHUB_OUTPUT)"

      # - id: view_outputs2
      #   name: View Outputs 2
      #   run:  |
      #     echo "$(tofu state pull | jq '.outputs.artifact_repo_uri.value')"
